apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: ocruzcarrillo-server-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: ocruzcarrillo-server
    spec:
      containers:
      - name: ocruzcarrillo-server
        image: ocruzcarrillo
        imagePullPolicy: Always
        ports:
        - containerPort: 3000
# vim: set ts=2 expandtab!: