apiVersion: v1
kind: Service
metadata:
  name: ocruzcarrillo-server
  labels:
    app: ocruzcarrillo-server
spec:
  selector:
    app: ocruzcarrillo-server
  ports:
  - port: 3000
    protocol: TCP
    nodePort: 30061
  type: LoadBalancer